Testing
AndrewTehan/Saloon pull request #20
Opened 2021-09-05 21:34 UTC by AndrewTehan

2021-09-24 21:15 UTC, longbeardman requested changes
minitest files (`test` folder) should be removed

2021-09-24 21:15 UTC, longbeardman commented on spec/requests/users_spec.rb
> +    user.confirm
seems to be redundant

2021-09-24 21:15 UTC, longbeardman commented on spec/requests/users_spec.rb
> +      expect(response.status).to eq(302)
check that user is removed from db

2021-09-24 21:15 UTC, longbeardman commented on spec/requests/users_spec.rb
> +  end
missing test cases (CRUD related)
1) create user
2) update user

2021-09-24 21:15 UTC, longbeardman commented on spec/requests/visits_spec.rb
> +    let(:visit) { FactoryBot.create(:visit, client: user) }
seems to redundant

2021-09-24 21:15 UTC, longbeardman commented on spec/requests/visits_spec.rb
> +      expect(response.status).to eq(302)
test case doesn't check that visit created

2021-09-24 21:15 UTC, longbeardman commented on spec/requests/visits_spec.rb
> +    let(:params) do { locale: I18n.locale, client_id: visit.client.id,
create `client`, `master` and `service` in `let`
```
let(:client) { create(:client) }
let(:service) { create(:service) }
let(:master) { create(:master, service_id: service.id) }
```

2021-09-24 21:15 UTC, longbeardman commented on spec/requests/visits_spec.rb
> +                      visit: { client_id: visit.client.id,
params may be hardcored

2021-09-24 21:15 UTC, longbeardman commented on spec/requests/visits_spec.rb
> +      expect(response.status).to eq(302)
this test case shows that it's possible to create visits for the same date time.
this should be validated

2021-09-24 21:15 UTC, longbeardman commented on spec/requests/visits_spec.rb
> +require 'rails_helper'
run rubocop

2021-09-24 21:15 UTC, longbeardman commented on spec/requests/visits_spec.rb
> +      delete :destroy, params: params
check if visit removed from db

2021-09-24 21:15 UTC, longbeardman commented on spec/requests/visits_spec.rb
> +  end
missing test case for disabling visit editing after visit got confirmed

2021-09-28 06:51 UTC, AndrewTehan commented on spec/requests/visits_spec.rb
> +  end
не получилось написать тест. тесткейс закомментирован

2021-10-06 14:54 UTC, merged